# Generated by Django 3.0.3 on 2020-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200312_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out For Delivery', 'Out For Delivery'), ('delivered', 'Delivered')], max_length=20, null=True),
        ),
    ]
